version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_c
    hostname: api
    command: npm run start:dev
    # env_file:
    #   - ./api/.env
    depends_on:
      - database
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  database:
    image: postgres:14-alpine
    container_name: db_c
    hostname: db
    env_file: ./api/.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  backup:
    image: postgres:latest
    volumes:
      - ./api/scripts:/api/scripts
    environment:
      - PGPASSWORD=todoleloup
    command: sh -c 'pg_dump -h database -U todoleloup -d todoleloup > ./api/scripts/backup.sql && sleep 86400'
    restart: unless-stopped

volumes:
  db_data:
